package main.oop;

/**
 * Created by ekaterina on 19.02.2017.
 */
public enum Status {
    SUPERLARGE_CITY,LARGEST_CITY, LARGE_CITY, BIG_CITY, MEDIUM_CITY, SMALL_CITY_VILLAGE,
    LARGE_RURAL_SETTLEMENT, BIG_RURAL_SETTLEMENT, MEDIUM_RURAL_SETTLEMENT, SMALL_RURAL_SETTLEMENT
}
